-- SwingEngine PostgreSQL database and schema.
--
-- Normally apply this through scripts/setup_database.sh. Direct psql usage is
-- retained for environments that do not use the local postgres system account.
--
-- Run this file with psql while connected to an administrative/maintenance
-- database (normally "postgres"). The connected role must have CREATEDB for
-- the first run. If swingengine_owner is supplied, that role must already
-- exist and the connected role must be allowed to SET ROLE to it.
--
-- Examples:
--   psql -X --dbname="$POSTGRES_ADMIN_URL" --file=database/schema.sql
--   psql -X --dbname="$POSTGRES_ADMIN_URL" \
--     --variable=swingengine_database=swingengine \
--     --variable=swingengine_owner=swingengine_app \
--     --file=database/schema.sql
--
-- The defaults are:
--   swingengine_database = swingengine
--   swingengine_owner    = the role running this script

\set ON_ERROR_STOP on

\if :{?swingengine_database}
\else
  \set swingengine_database swingengine
\endif

\if :{?swingengine_owner}
\else
  SELECT current_user AS swingengine_owner
  \gset
\endif

-- CREATE DATABASE cannot run inside a transaction. \gexec executes the
-- generated statement only when the requested database does not yet exist.
SELECT format(
    'CREATE DATABASE %I OWNER %I',
    :'swingengine_database',
    :'swingengine_owner'
)
WHERE NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_database
    WHERE datname = :'swingengine_database'
)
\gexec

-- Reuse the current host, port, user, password, and SSL settings.
\connect :swingengine_database

BEGIN;

-- Do not wait forever for locks in production.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '5min';

-- Fail rather than allowing two deployments to modify this schema at once.
DO $$
BEGIN
    IF NOT pg_try_advisory_xact_lock(
        hashtextextended('swingengine:public-schema', 0)
    ) THEN
        RAISE EXCEPTION
            'Another SwingEngine schema deployment is already running';
    END IF;
END
$$;

SET ROLE :"swingengine_owner";

CREATE TABLE IF NOT EXISTS public.tracker (
    tracker_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name TEXT NOT NULL,
    asset_symbol TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tracker_details (
    tracker_details_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracker_id BIGINT NOT NULL,
    has_momentum BOOLEAN NOT NULL DEFAULT FALSE,
    is_order_created BOOLEAN NOT NULL DEFAULT FALSE,
    is_approved_for_order BOOLEAN NOT NULL DEFAULT FALSE,
    amount_allocated DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT tracker_details_tracker_fk
        FOREIGN KEY (tracker_id)
        REFERENCES public.tracker (tracker_id),
    CONSTRAINT tracker_details_amount_allocated_nonnegative
        CHECK (amount_allocated >= 0)
);

-- PostgreSQL does not automatically index the referencing side of a foreign
-- key. This index keeps tracker lookups and parent-row checks efficient.
CREATE INDEX IF NOT EXISTS tracker_details_tracker_id_idx
    ON public.tracker_details (tracker_id);

COMMENT ON TABLE public.tracker IS
    'Assets monitored by SwingEngine.';
COMMENT ON TABLE public.tracker_details IS
    'Momentum, order, approval, and allocation state for tracked assets.';

RESET ROLE;

COMMIT;

\echo 'SwingEngine database schema is up to date.'
