-- SwingEngine PostgreSQL database and schema.
--
-- Normally apply this through scripts/setup_database.sh. Direct psql usage is
-- retained for environments that do not use the local postgres system account.
--
-- Run this file with psql while connected to an administrative/maintenance
-- database (normally "postgres"). The connected role must have CREATEDB for
-- the first run. If swingengine_owner is supplied, that role must already
-- exist and the connected role must be allowed to SET ROLE to it.
--
-- Examples:
--   psql -X --dbname="$POSTGRES_ADMIN_URL" --file=database/schema.sql
--   psql -X --dbname="$POSTGRES_ADMIN_URL" \
--     --variable=swingengine_database=swingengine \
--     --variable=swingengine_owner=swingengine_app \
--     --file=database/schema.sql
--
-- The defaults are:
--   swingengine_database = swingengine
--   swingengine_owner    = the role running this script

\set ON_ERROR_STOP on

\if :{?swingengine_database}
\else
  \set swingengine_database swingengine
\endif

\if :{?swingengine_owner}
\else
  SELECT current_user AS swingengine_owner
  \gset
\endif

-- CREATE DATABASE cannot run inside a transaction. \gexec executes the
-- generated statement only when the requested database does not yet exist.
SELECT format(
    'CREATE DATABASE %I OWNER %I',
    :'swingengine_database',
    :'swingengine_owner'
)
WHERE NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_database
    WHERE datname = :'swingengine_database'
)
\gexec

-- Reuse the current host, port, user, password, and SSL settings.
\connect :swingengine_database

BEGIN;

-- Do not wait forever for locks in production.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '5min';

-- Fail rather than allowing two deployments to modify this schema at once.
DO $$
BEGIN
    IF NOT pg_try_advisory_xact_lock(
        hashtextextended('swingengine:public-schema', 0)
    ) THEN
        RAISE EXCEPTION
            'Another SwingEngine schema deployment is already running';
    END IF;
END
$$;

SET ROLE :"swingengine_owner";

-- Upgrade the original tracker/tracker_details structure without discarding
-- tracked assets or their state. Renaming the tables and columns also updates
-- the foreign key references maintained by PostgreSQL.
DO $$
BEGIN
    IF to_regclass('public.tracker_details') IS NOT NULL THEN
        IF to_regclass('public.tracker') IS NULL THEN
            RAISE EXCEPTION
                'Cannot migrate tracker_details: tracker does not exist';
        END IF;

        IF to_regclass('public.assets') IS NOT NULL THEN
            RAISE EXCEPTION
                'Cannot migrate legacy tracker: assets already exists';
        END IF;

        ALTER TABLE public.tracker RENAME TO assets;
        ALTER TABLE public.assets RENAME COLUMN tracker_id TO asset_id;
        ALTER TABLE public.assets
            RENAME COLUMN asset_symbol TO trading_symbol;
        ALTER TABLE public.assets
            RENAME CONSTRAINT tracker_pkey TO assets_pkey;
        ALTER SEQUENCE IF EXISTS public.tracker_tracker_id_seq
            RENAME TO assets_asset_id_seq;

        ALTER TABLE public.tracker_details RENAME TO tracker;
        ALTER TABLE public.tracker RENAME COLUMN tracker_id TO asset_id;
        ALTER TABLE public.tracker
            RENAME CONSTRAINT tracker_details_pkey TO tracker_pkey;
        ALTER TABLE public.tracker
            RENAME CONSTRAINT tracker_details_tracker_fk TO tracker_asset_fk;
        ALTER TABLE public.tracker
            RENAME CONSTRAINT tracker_details_amount_allocated_nonnegative
            TO tracker_amount_allocated_nonnegative;
        ALTER SEQUENCE IF EXISTS
            public.tracker_details_tracker_details_id_seq
            RENAME TO tracker_tracker_details_id_seq;
        ALTER INDEX IF EXISTS public.tracker_details_tracker_id_idx
            RENAME TO tracker_asset_id_idx;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name TEXT NOT NULL,
    trading_symbol TEXT NOT NULL,
    instrument_key TEXT
);

-- CREATE TABLE IF NOT EXISTS does not add columns during an upgrade.
ALTER TABLE public.assets
    ADD COLUMN IF NOT EXISTS instrument_key TEXT;

CREATE TABLE IF NOT EXISTS public.tracker (
    tracker_details_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    has_momentum BOOLEAN NOT NULL DEFAULT FALSE,
    is_order_created BOOLEAN NOT NULL DEFAULT FALSE,
    is_approved_for_order BOOLEAN NOT NULL DEFAULT FALSE,
    amount_allocated DOUBLE PRECISION NOT NULL DEFAULT 0,
    added_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT tracker_asset_fk
        FOREIGN KEY (asset_id)
        REFERENCES public.assets (asset_id),
    CONSTRAINT tracker_amount_allocated_nonnegative
        CHECK (amount_allocated >= 0)
);

ALTER TABLE public.tracker
    ADD COLUMN IF NOT EXISTS added_date
        DATE NOT NULL DEFAULT CURRENT_DATE;

-- Commands address both tables by trading symbol, so keep symbols and tracker
-- membership unambiguous.
CREATE UNIQUE INDEX IF NOT EXISTS assets_trading_symbol_unique_idx
    ON public.assets (upper(trading_symbol));
CREATE UNIQUE INDEX IF NOT EXISTS tracker_asset_id_unique_idx
    ON public.tracker (asset_id);

-- PostgreSQL does not automatically index the referencing side of a foreign
-- key. This index keeps asset lookups and parent-row checks efficient.
CREATE INDEX IF NOT EXISTS tracker_asset_id_idx
    ON public.tracker (asset_id);

COMMENT ON TABLE public.assets IS
    'Assets monitored by SwingEngine.';
COMMENT ON TABLE public.tracker IS
    'Momentum, order, approval, and allocation state for tracked assets.';

RESET ROLE;

COMMIT;

\echo 'SwingEngine database schema is up to date.'
